### ISSUE TITLE
IpUtils.GetLocalIpAddress() failure

### ISSUE THREAD

**Issue by svantreeck** [openzipkin/zipkin4net#49]
When I added this to a project deployed in a docker swarm, I ended up losing tracing.  From what I can tell, the [Dns.GetHostName()](https://github.com/criteo/zipkin4net/blob/master/zipkin4net/Criteo.Profiling.Tracing/Utils/IpUtils.cs#L21) call is returning the docker container id, which isn't resolving to a Host Entry.  The error is at the bottom of this

I've tried a few workarounds to populate the span's Endpoint by recording a LocalAddr Annotation (`trace.Record(Annotations.LocalAddr(endpoint));`); however, it looks like the static constructor on SerializerUtils is called regardless of the Span's endpoint being set.

I was sort of going down a few different paths for remedying this and wondering if you have a preference on implementation or other ideas...
1.) Catch the Exception in `IpUtils.GetLocalIpAddress` and if one occurs, return the Loopback address
2.) Switch the detection to a variation of the answer at http://stackoverflow.com/a/27376368.  I'm not a huge fan of this because hitting google's DNS probably brings different issues
3.) Allow a user to inject an override for the default address (through TraceManager?)

```
warn: Tracing[0]
      An error occured while recording the annotation: System.TypeInitializationException: The type initializer for 'Criteo.Profiling.Tracing.Tracers.Zipkin.SerializerUtils' threw an exception. ---> System.AggregateException: One or more errors occurred. (No such device or address) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: No such device or address
         at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
         at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult)
         at System.Net.Dns.<>c.<GetHostEntryAsync>b__16_1(IAsyncResult asyncResult)
         at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
         --- End of inner exception stack trace ---
         at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
         at Criteo.Profiling.Tracing.Utils.IpUtils.GetLocalIpAddress()
         at Criteo.Profiling.Tracing.Tracers.Zipkin.SerializerUtils..cctor()
         --- End of inner exception stack trace ---
         at Criteo.Profiling.Tracing.Tracers.Zipkin.ThriftSpanSerializer.ConvertToThrift(Span span)
         at Criteo.Profiling.Tracing.Tracers.Zipkin.ThriftSpanSerializer.SerializeTo(Stream stream, Span span)
         at Criteo.Profiling.Tracing.Tracers.Zipkin.ZipkinTracer.LogSpan(Span span)
         at Criteo.Profiling.Tracing.Tracers.Zipkin.ZipkinTracer.Record(Record record)
         at Criteo.Profiling.Tracing.TraceManager.Push(Record record)
```

**Comment by fedj** [comment]
Hi @svantreeck,

Thanks a lot for the issue, I must admit this is not a case we tried.
I agree with you that the second solution is definitely something I would go for (even if I recognize it should work).
I was thinking a bit recently about LocalAddr and I'm not sure it's really useful to keep this API (you're always on the same machine when sending spans with a tracer).
However, since LocalAddr is an existing API, I would suggest to put in place the first solution for the moment. We'll probably iterate a bit later on this topic though.

Do you want to do a PR or do you want me to do it ?

**Comment by svantreeck** [comment]
I'll do a PR on it
