### ISSUE TITLE
NuGet package Criteo.Profiling.Tracing.Middleware 1.0 Update

### ISSUE THREAD

**Issue by tai-yi** [openzipkin/zipkin4net#78]
Please update the packege .
In this version ,It depend Criteo.Profiling.Tracing (version >=0.3.1) 
But  Criteo.Profiling.Tracing 0.3.4 is diffenent from the 0.3.5.
In 0.3.5 some methods have been removed.

When you use Criteo.Profiling.Tracing.Middleware 1.0( current max version) and Criteo.Profiling.Tracing 0.3.5 (current max version)  ,  you can see an error 'Method not found: 'System.String Criteo.Profiling.Tracing.Transport.ZipkinHttpHeaders.EncodeLongToHexString(Int64)''

In addtion, I run my application in docker container , I must add the parameter '--privileged'. 
It looks like write some logs to a file .
How can I configure the output target  or donot write file ? 

Thanks

**Comment by fedj** [comment]
Hi @tiayi,

Thanks a lot for the bug report. Nuget has been updated with a dependency on the latest Criteo.Profiling.Tracing version (0.3.5) and you can find it [here](https://www.nuget.org/packages/Criteo.Profiling.Tracing.Middleware/0.2.0).
The commit bumping the version is [this one](https://github.com/criteo/zipkin4net/commit/f4118c6fa726f072c75fd5e6e204640285dfb5f6).

For the privileged mode, I'm not really familiar with docker but isn't it because the program opens a socket ?
I'm sorry for the delay of response but I have very limited access to my computer until Monday.

**Comment by tai-yi** [comment]
Hi @fedj ,
The application run in docker container ,must use privileged mode.
This is from System.Net.NetworkInformation.NetworkInterfacePal.GetIsNetworkAvailable().

This is log.

Hosting environment: Production
Content root path: /app
Now listening on: http://+:80
Application started. Press Ctrl+C to shut down.

Unhandled Exception: System.UnauthorizedAccessException: Access to the path '/sys/class/net/lo/operstate' is denied. ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.UnixFileStream.CheckFileCall(Int64 result, Boolean ignoreNotSupported)
   at System.IO.UnixFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.UnixFileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetOperationalStatus(String name)
   at System.Net.NetworkInformation.LinuxNetworkInterface..ctor(String name)
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetOrCreate(Dictionary`2 interfaces, String name)
   at System.Net.NetworkInformation.LinuxNetworkInterface.<>c__DisplayClass5_0.<GetLinuxNetworkInterfaces>b__2(String name, LinkLayerAddressInfo* llAddr)
   at Interop.Sys.EnumerateInterfaceAddresses(IPv4AddressDiscoveredCallback ipv4Found, IPv6AddressDiscoveredCallback ipv6Found, LinkLayerAddressDiscoveredCallback linkLayerFound)
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces()
   at System.Net.NetworkInformation.NetworkInterfacePal.GetIsNetworkAvailable()
   at Criteo.Profiling.Tracing.Utils.IpUtils.GetLocalIpAddress()
   at Criteo.Profiling.Tracing.Tracers.Zipkin.SerializerUtils.GetLocalEndPointOrDefault()

**Comment by tiayi** [comment]
Hi @fedj 
There is another error here.
evn:  
      AspNetCore version : 1.0
      docker image: microsoft/aspnetcore:1.0

log:
System.Exception: Http Code:Redirect ; Message:Moved Temporarily
   at UI.ApiClientHelper.<StringContent>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at UI.ApiClientHelper.<Get>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at UI.Controllers.HomeController.<Index2>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Criteo.Profiling.Tracing.Utils.TraceHelper.<TracedActionAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Criteo.Profiling.Tracing.Middleware.TracingMiddleware.<>c__DisplayClass0_0.<<UseTracing>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()

**Comment by fedj** [comment]
@tiayi Did you try with version 0.2 ? It should be fixed normally.

**Comment by tai-yi** [comment]
@fedj 
Yes, it's worked. 
Thanks

**Comment by fedj** [comment]
Thanks a lot for this issue.
